---

kind: pipeline
type: docker
name: FullBuild

platform:
  os: linux
  arch: amd64

steps:
- name: Lint Dockerfile
  image: hadolint/hadolint:latest-alpine
  pull: if-not-exists
  commands:
    - hadolint --version
    - hadolint base-fullbuild/Dockerfile*

- name: FullBuild
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/borgmatic-docker
    purge: true
    compress: true
    use_cache: true
    cache_from: "modem7/borgmatic-docker:latest"
    Dockerfile: base-fullbuild/Dockerfile
    context: base-fullbuild/
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      - linux/arm/v6
      - linux/arm/v7
      - linux/arm64/v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest
      - 1.5.21

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  event:
    - custom

---

kind: pipeline
type: docker
name: dockercli

platform:
  os: linux
  arch: amd64

steps:
- name: Lint Dockerfile
  image: hadolint/hadolint:latest-alpine
  pull: if-not-exists
  commands:
    - hadolint --version
    - hadolint base-dockercli/Dockerfile*

- name: Docker-CLI 
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/borgmatic-docker
    purge: true
    compress: true
    use_cache: true
    cache_from: "modem7/borgmatic-docker:dockercli"
    Dockerfile: base-dockercli/Dockerfile
    context: base-dockercli/
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      - linux/arm/v6
      - linux/arm/v7
      - linux/arm64/v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - dockercli

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  event:
    - custom

depends_on:
  - FullBuild

---

kind: pipeline
type: docker
name: LiveInstall

platform:
  os: linux
  arch: amd64

steps:
- name: Lint Dockerfile
  image: hadolint/hadolint:latest-alpine
  pull: if-not-exists
  commands:
    - hadolint --version
    - hadolint base-liveinstall/Dockerfile*

- name: LiveInstall  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/borgmatic-docker
    purge: true
    compress: true
    use_cache: true
    cache_from: "modem7/borgmatic-docker:liveinstall"
    Dockerfile: base-liveinstall/Dockerfile
    context: base-liveinstall/
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      - linux/arm/v6
      - linux/arm/v7
      - linux/arm64/v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - liveinstall

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  event:
    - custom

depends_on:
  - FullBuild
